[_1]
time="2018年12月3日12点53分"
dialogue="司司：以后你要看到美女就自动过滤，知道了吗|双双：那就都过滤不了了，就只把你过滤了|司司：为什么|双双：因为在我眼里，只有你是美女"

[_2]
time="2018年12月3日19点46分"
dialogue="司司：你不能累坏啦，因为啥你知道吗？|双双：不知道|司司：因为我会心疼呀"

[_3]
time="2018年12月3日20点05分"
dialogue="双双：我们去看明年的灯光节，到时候你看着天，我看着你|司司：看着我，我不会表演哦|双双：不用表演，我就想静静看着静静||司司：然后旁边的人就说，你们看，那两沙雕|双双：我又听不到，我眼里只有你"

[_4]
time="2018年12月3日20点25分"
dialogue="司司：今天腿扭了一下|司司：可能因为没有你，我才会扭到吧"

[_5]
time="2018年12月3日20点37分"
dialogue="司司：仙女啥都不缺|双双：不，你缺我的小心心|司司：要好多好多小心心"

[_6]
time="2018年12月3日20点40分"
dialogue="司司：你猜我有啥就够啦|双双：有什么呢|司司：我只要有仙男呀"

[_7]
time="2018年12月3日20点49分"
dialogue="司司：你喜欢的东西吗|双双：有啊|司司：是手办吗|双双：你呀"

[_8]
time="2018年12月3日21点00分"
dialogue="司司：我才六岁|司司：你要养大吗？|双双：要|双双：要养到老"

[_9]
time="2018年12月3日22点08分"
dialogue="双双：你要什么都给你|司司：要什么都给吗|司司：那我要天上的星星哈哈哈哈|双双：你在我眼里就是，星空下最亮的星"

[_10]
time="2018年12月3日22点24分"
dialogue="司司：你为啥会在星球看到我呀|双双：是命运的指引"

[_11]
time="2018年12月3日22点39分"
dialogue="双双：我那么大还没去旅游过|司司：以后一起带你去|司司：旅游"

[_12]
time="2018年12月3日22点54分"
dialogue="那100件事|我们要|每做一件|拍一张照片留念|以后做出相册|给每一个朋友看"