[_1]
time="2018年12月3日12点53分"
dialogue="司司：以后你要看到美女就自动过滤，知道了吗|双双：那就都过滤不了了，就只把你过滤了|司司：为什么|双双：因为在我眼里，只有你是美女"

[_2]
time="2018年12月3日19点46分"
dialogue="司司：你不能累坏啦，因为啥你知道吗？|双双：不知道|司司：因为我会心疼呀"

[_3]
time="2018年12月3日20点05分"
dialogue="双双：我们去看明年的灯光节，到时候你看着天，我看着你|司司：看着我，我不会表演哦|双双：不用表演，我就想静静看着静静||司司：然后旁边的人就说，你们看，那两沙雕|双双：我又听不到，我眼里只有你"

[_4]
time="2018年12月3日20点25分"
dialogue="司司：今天腿扭了一下|司司：可能因为没有你，我才会扭到吧"

[_5]
time="2018年12月3日20点37分"
dialogue="司司：仙女啥都不缺|双双：不，你缺我的小心心|司司：要好多好多小心心"

[_6]
time="2018年12月3日20点40分"
dialogue="司司：你猜我有啥就够啦|双双：有什么呢|司司：我只要有仙男呀"

[_7]
time="2018年12月3日20点49分"
dialogue="司司：你喜欢的东西吗|双双：有啊|司司：是手办吗|双双：你呀"

[_8]
time="2018年12月3日21点00分"
dialogue="司司：我才六岁|司司：你要养大吗？|双双：要|双双：要养到老"

[_9]
time="2018年12月3日22点08分"
dialogue="双双：你要什么都给你|司司：要什么都给吗|司司：那我要天上的星星哈哈哈哈|双双：你在我眼里就是，星空下最亮的星"

[_10]
time="2018年12月3日22点24分"
dialogue="司司：你为啥会在星球看到我呀|双双：是命运的指引"

[_11]
time="2018年12月3日22点39分"
dialogue="双双：我那么大还没去旅游过|司司：以后一起带你去|司司：旅游"

[_12]
time="2018年12月3日22点54分"
dialogue="那100件事|我们要|每做一件|拍一张照片留念|以后做出相册|给每一个朋友看"

[_13]
time="2018年12月6日23点01分"
dialogue="司司：谁不要脸|司司：你说|双双：我不要脸"

[_14]
time="2018年12月6日22点40分"
dialogue="司司：谁最喜欢仙女|双双：仙男|司司：仙男是谁|双双：我|司司：你干什么|双双：我最喜欢仙女"

[_15]
time="2018年12月6日22点29分"
dialogue="司司：你想听我声音的时候可以打给我|双双：那我可以现在打吗|司司：才一会就想啦|双双：那我过一秒再打|司司：太久啦，一秒那么长|双双：你想听我声音的时候也可以打哦|司司：那我也现在打"

[_16]
time="2018年12月6日22点21分"
dialogue="司司：我的声音系不系好难听|双双：我很喜欢，有点甜甜的感觉"

[_17]
time="2018年12月4日21点26分"
dialogue="双双：我想和你去旅游，然后你看风景我看你|司司：那你有一天会腻的，因为老系我|双双：那就也看一下来旅游的美女吧|司司：哼，不可以看，闭上眼睛|双双：闭上眼睛怎么办，什么都看不到，会撞人的|司司：我牵着你走啊"

[_18]
time="2018年12月4日21点02分"
dialogue="司司：你以后要叫我静静吗？那么多静静|双双：我怎么会叫你静静，我都是叫小仙女的好吗|司司：见面也叫小仙女吗|双双：还要在前面加两个字，我的小仙女"

[_19]
time="2018年12月6日20点21分"
dialogue="双双：从没拿过加班费|司司：你老不加班对吧|双双：以前想懒，不想加|双双：现在想你，不想加"










